//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int CompanyID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> VendorCode { get; set; }
    }
}
