//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItems
    {
        public string OrderNo { get; set; }
        public Nullable<int> BrandCode { get; set; }
        public string ModelNo { get; set; }
        public Nullable<int> ColorCode { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
    }
}
