//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesItems
    {
        public string ReceiptNo { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public string ProductCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ServiceBillNo { get; set; }
    }
}
