//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePro
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffExpense
    {
        public int TableKey { get; set; }
        public int StaffId { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<double> ExpenseAmount { get; set; }
        public string Description { get; set; }
    }
}
